(() => {
  const month = new Date().getMonth() + 1;
  const articles = [
    {id:'billing',base:20,months:[4,5,6],category:'VYÚČTOVANIE · PENIAZE',updated:'09/2026',title:'Ako čítať ročné vyúčtovanie bez zbytočnej paniky',desc:'Čo skontrolovať ako prvé, kde hľadať spotreby a čo urobiť, ak vám niečo nesedí.',html:`<p>Ročné vyúčtovanie nie je len číslo „preplatok alebo nedoplatok“. Je to kontrola toho, koľko ste počas roka zaplatili na zálohách a aké skutočné náklady boli na váš byt rozpočítané.</p><h3>Čo skontrolovať ako prvé</h3><ul><li><b>Uhradené zálohy</b> – či sedia s vašimi reálnymi platbami počas roka.</li><li><b>Stavy meradiel</b> – najmä voda a teplo.</li><li><b>Spôsob rozpočítania</b> – niektoré položky sa delia podľa spotreby, iné podľa plochy, počtu osôb alebo spoluvlastníckeho podielu.</li><li><b>Preplatok alebo nedoplatok</b> – je výsledkom rozdielu medzi zaplatenými zálohami a skutočnými nákladmi.</li></ul><div class="softnote"><b>Termín správcu:</b> správca je povinný najneskôr do 31. mája nasledujúceho roka predložiť správu o činnosti za dom a vykonať vyúčtovanie.</div><h3>Ak niečo nesedí</h3><p>Napíšte nám konkrétne, ktorú položku namietate a prečo. Najlepšie je uviesť dom, byt, názov položky a číslo alebo údaj, ktorý považujete za nesprávny. Zákon č. 182/1993 Z. z. neurčuje jednu všeobecnú 14-dňovú reklamačnú lehotu pre každé vyúčtovanie; osobitná lehota môže vyplývať zo zmluvy alebo pravidiel konkrétneho domu.</p>`,sources:[['Zákon 182/1993 Z. z. · Slov-Lex','https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/1993/182/']]},
    {id:'heat',base:25,months:[1,2,3,9,10,11,12],category:'TEPLO · ENERGIE',updated:'09/2026',title:'Za teplo musí platiť aj ten, kto má zavretý radiátor',desc:'Prečo nulová spotreba na radiátore neznamená nulový účet za vykurovanie.',html:`<p>Byt v bytovom dome nie je samostatná termoska. Teplo prechádza stenami, stropmi, rozvodmi aj spoločnými konštrukciami. Preto sa náklady na vykurovanie nerozdeľujú iba podľa čísla na pomerovom rozdeľovači alebo merači.</p><h3>Základná a spotrebná zložka</h3><p>Pri bytoch s pomerovými rozdeľovačmi alebo určenými meradlami je podľa aktuálnej vyhlášky základná zložka štandardne <b>60 %</b>. Vlastníci môžu rozhodnúť o inom podiele, ale základná zložka nemôže byť nižšia ako <b>30 %</b>. Zvyšok tvorí spotrebná zložka.</p><h3>Načo je hranica 2,85</h3><p>Ak je pomer najvyššieho a najnižšieho špecifického nákladu na vykurovanie v dome vyšší ako <b>2,85</b>, základná zložka sa upraví tak, aby bol rozdiel medzi bytmi primeranejší.</p><div class="softnote"><b>Prakticky:</b> úplne zavrieť radiátory nemusí znamenať nulový účet. Časť tepla dostávate nepriamo z domu.</div>`,sources:[['Vyhláška 503/2022 Z. z. · Slov-Lex','https://www.slov-lex.sk/ezbierky-fe/pravne-predpisy/SK/ZZ/2022/503/']]},
    {id:'rights',base:30,months:[7,8],category:'VLASTNÍK · PRÁVA A POVINNOSTI',updated:'09/2026',title:'10 vecí, ktoré by mal vedieť každý vlastník bytu',desc:'Hlasovanie, dokumenty, spoločné časti domu, platby aj lehoty – bez právnickej reči.',html:`<p>Vlastník bytu nie je iba zákazník správcu. Je zároveň spoluvlastníkom spoločných častí a zariadení domu a má právo aj povinnosť podieľať sa na jeho správe.</p><ul><li>Máte právo zúčastňovať sa na správe domu a hlasovaním rozhodovať o spoločných veciach.</li><li>Platné rozhodnutia vlastníkov sú záväzné aj pre tých, ktorí nehlasovali alebo hlasovali proti.</li><li>Výsledok schôdze alebo písomného hlasovania sa zverejňuje spôsobom v dome obvyklým.</li><li>Prehlasovaný vlastník sa môže obrátiť na súd do <b>30 dní od oznámenia výsledku hlasovania</b>; ak sa o výsledku nemohol dozvedieť, najneskôr do troch mesiacov.</li><li>Máte povinnosť riadne a včas platiť preddavky do fondu aj úhrady za služby.</li><li>Pri zásahu do spoločných častí, rozvodov alebo bezpečnosti domu treba postup vopred konzultovať.</li><li>Správca hospodári s peniazmi vlastníkov a musí uprednostňovať ich záujmy.</li><li>Pri obstarávaní má správca dojednávať čo najvýhodnejšie podmienky v prospech vlastníkov.</li><li>O dôležitých investíciách, úveroch a zásadných zmenách rozhodujú vlastníci.</li><li>Keď si nie ste istí, pýtajte sa skôr, než urobíte nevratný zásah.</li></ul>`,sources:[['Zákon 182/1993 Z. z. · Slov-Lex','https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/1993/182/']]},
    {id:'evoting',base:26,months:[5,6,9,10,11],category:'HLASOVANIE · ELEKTRONICKY',updated:'09/2026',title:'Elektronické hlasovanie vlastníkov: ako funguje a kedy je platné',desc:'Čo musí vedieť správca overiť, čo musí potvrdiť a prečo obyčajný náhodný e-mail ešte nemusí byť hlasom.',html:`<p>Elektronické hlasovanie je dnes zákonnou súčasťou písomného hlasovania. Hlas musí byť priradený ku konkrétnemu vlastníkovi a ku konkrétnej otázke tak, aby nevznikla pochybnosť, kto a ako hlasoval.</p><h3>Čo musí byť splnené</h3><ul><li>vlastník oznámi správcovi alebo spoločenstvu svoju elektronickú adresu,</li><li>spôsob hlasovania musí umožniť jednoznačne overiť účasť vlastníka bez možnosti zámeny,</li><li>z hlasu musí byť zrejmá určitá vôľa pri každej konkrétnej otázke,</li><li>hlasovanie a výsledky musia byť chránené pred neoprávneným zásahom,</li><li>správca musí bez zbytočného odkladu potvrdiť prijatie elektronického hlasu rovnakým spôsobom.</li></ul><div class="softnote"><b>Dôležité:</b> ak vlastník hlasuje elektronicky viackrát, platí jeho posledný elektronický hlas. Ak však hlasuje aj na papierovej hlasovacej listine, na elektronický hlas sa neprihliada.</div>`,sources:[['Zákon 182/1993 Z. z. · § 14 a § 14a','https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/1993/182/']]},
    {id:'water',base:24,months:[6,7,8],category:'VODA · POPRAD A SVIT',updated:'09/2026',title:'Prečo sa za vodu platí aj fixná zložka',desc:'Ako funguje dvojzložková cena vodného a stočného a čo dnes účtuje PVPS v našom regióne.',html:`<p>Vodné a stočné už nie je iba cena za každý spotrebovaný kubík. Dvojzložková cena pozostáva z <b>fixnej zložky za odberné miesto</b> a z <b>variabilnej zložky podľa skutočne odobratého množstva vody</b>.</p><h3>Za čo je fixná zložka</h3><p>Fixná časť pokrýva náklady spojené s existenciou a pripravenosťou odberného miesta – napríklad meradlo, jeho overovanie a opravy, odpočty a udržiavanie potrebnej kapacity siete.</p><h3>Aktuálne ceny PVPS</h3><p>Podtatranská vodárenská prevádzková spoločnosť má od <b>15. júna 2026</b> novú regulovanú cenu. Variabilná zložka vodného je <b>2,2151 € s DPH za m³</b> a variabilná zložka stočného <b>1,9108 € s DPH za m³</b>.</p><div class="softnote"><b>V bytovom dome:</b> vodárenská spoločnosť fakturuje odberné miesto domu podľa hlavného meradla. Náklady domu sa potom rozpočítajú medzi vlastníkov.</div>`,sources:[['ÚRSO · dvojzložková cena vody','https://www.urso.gov.sk/205993-sk/voda/'],['PVPS · aktuálne ceny','https://pvpsas.sk/cena-vody-dvojzlozkova/']]},
    {id:'reconstruction2026',base:22,months:[3,4,5,9],category:'REKONŠTRUKCIA · STAVEBNÝ ZÁKON',updated:'09/2026',title:'Prerábka bytu po novom: čo treba riešiť pred začatím prác',desc:'Nie každá výmena obkladu potrebuje povolenie, ale zásah do nosných konštrukcií či spoločných častí už nemožno brať na ľahkú váhu.',html:`<p>Nový Stavebný zákon č. 25/2025 Z. z. sprísnil dôraz na bezpečnú prevádzku a údržbu stavieb.</p><h3>Nie každá prerábka má rovnaký režim</h3><p>Bežná údržba a výmena nepodstatných vnútorných prvkov môže byť bez ohlásenia. Iná situácia nastáva, ak práce môžu ovplyvniť stabilitu, protipožiarnu bezpečnosť, vzhľad domu, spoločné rozvody alebo iné spoločné časti domu.</p><ul><li>búranie alebo úprava nosnej konštrukcie – najprv odborné posúdenie a príslušný zákonný postup,</li><li>zmena okien, balkóna, fasády alebo vonkajšieho vzhľadu – môže sa týkať spoločných častí a rozhodovania vlastníkov,</li><li>zásah do spoločných rozvodov kúrenia, vody, plynu či elektriny – vždy vopred konzultovať so správcom,</li><li>bežné vnútorné povrchy, obklady a podlahy – spravidla jednoduchší režim.</li></ul><div class="softnote"><b>Praktické pravidlo KUSIMA:</b> ak chcete búrať, meniť rozvody, radiátory, okná, balkón alebo čokoľvek, čo môže zasiahnuť do spoločnej časti domu, ozvite sa nám ešte pred objednaním prác.</div>`,sources:[['Stavebný zákon 25/2025 Z. z.','https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/2025/25/'],['Zákon 182/1993 Z. z.','https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/1993/182/']]},
    {id:'money',base:18,months:[1,11,12],category:'PENIAZE DOMU · BEZPEČNOSŤ',updated:'09/2026',title:'Komu patria peniaze na účte domu a ako ich zákon chráni',desc:'Účet domu nie je účtom správcu. Zákon presne oddeľuje peniaze vlastníkov od majetku správcovskej firmy.',html:`<p>Peniaze, ktoré vlastníci posielajú na služby a do fondu prevádzky, údržby a opráv, nie sú majetkom správcovskej spoločnosti. Zákon ich označuje ako <b>majetok vlastníkov</b> a prikazuje ich viesť oddelene od vlastných peňazí správcu.</p><ul><li>viesť samostatné analytické účty osobitne za každý spravovaný dom,</li><li>prostriedky vlastníkov viesť oddelene od účtov správcu v banke a osobitne pre každý dom,</li><li>používať majetok vlastníkov iba na činnosti bezprostredne súvisiace so správou daného domu,</li><li>nevyužiť tieto prostriedky vo vlastný prospech ani v prospech tretích osôb.</li></ul><div class="softnote"><b>Čo z toho vyplýva:</b> správca má k účtu dispozičné oprávnenie na výkon správy, ale peniaze mu nepatria.</div>`,sources:[['Zákon 182/1993 Z. z. · § 8','https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/1993/182/']]},
    {id:'heatingseason',base:60,months:[9,10],category:'VYKUROVACIA SEZÓNA · PRAKTICKY',updated:'09/2026',title:'Kedy sa v bytovke začne kúriť a prečo radiátor nemusí byť stále teplý',desc:'Vykurovacie obdobie sa začína v septembri, ale kúrenie sa nespúšťa podľa kalendára. Rozhoduje počasie a vnútorná teplota.',html:`<p>Prvý september neznamená, že radiátory musia byť automaticky horúce. Vyhláška určuje <b>vykurovacie obdobie spravidla od 1. septembra do 31. mája</b>, ale samotná dodávka tepla sa riadi vývojom vonkajšej teploty.</p><h3>Kedy sa začne kúriť</h3><p>Dodávateľ začne teplo na vykurovanie dodávať, ak priemerná denná vonkajšia teplota počas <b>dvoch po sebe nasledujúcich dní klesne pod 13 °C</b> a podľa predpovede nemožno očakávať, že nasledujúci deň vystúpi nad túto hranicu.</p><h3>Aká teplota má byť v byte</h3><p>Pre obytné miestnosti vyhláška uvádza 21 °C, pre kuchyňu 20 °C a pre kúpeľňu 24 °C, s určenou toleranciou dodávky.</p><div class="softnote"><b>Radiátor nie je teplomer miestnosti.</b> To, že je chvíľu vlažný alebo studený, ešte samo osebe neznamená poruchu.</div>`,sources:[['Vyhláška 152/2005 Z. z.','https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/2005/152/'],['Zákon 657/2004 Z. z.','https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/2004/657/']]},
    {id:'remote2027',base:45,months:[10,11,12,1],category:'MERADLÁ · DIAĽKOVÝ ODPOČET 2027',updated:'09/2026',title:'Diaľkový odpočet od roku 2027: čo je povinné a čo si môžu vlastníci rozhodnúť',desc:'Jedna vec je spôsob rozpočítania a druhá zákonná povinnosť mať meradlá a diaľkový odpočet. Nie je to to isté.',html:`<p>Pri diaľkových odpočtoch sa často miešajú dve rozdielne otázky: <b>ako sa náklad rozpočíta medzi byty</b> a <b>aké meranie musí byť v dome technicky zabezpečené</b>.</p><h3>Vykurovanie a teplá voda</h3><p>Pri zákonom určených prípadoch musí byť zabezpečené meranie u konečných spotrebiteľov a funkcia diaľkového odpočtu; pri existujúcich meradlách teplej vody je stanovený prechod na diaľkový odpočet do <b>1. januára 2027</b>, s výnimkou pre preukázanú technickú nemožnosť alebo nákladovú neprimeranosť.</p><h3>A čo studená voda?</h3><p>Všeobecná povinnosť „od 1. januára 2027 musia byť na diaľkový odpočet všetky bytové vodomery“ nie je presná. Uvedená povinnosť sa viaže na meranie tepla a teplej vody.</p><div class="softnote"><b>Jednoducho:</b> vlastníci môžu rozhodnúť o zákonom dovolenej variante rozpočítania, ale hlasovaním nemôžu vytvoriť výnimku zo zákona.</div>`,sources:[['Zákon 657/2004 Z. z.','https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/2004/657/'],['Zákon 321/2014 Z. z.','https://www.slov-lex.sk/ezbierky-fe/pravne-predpisy/SK/ZZ/2014/321/'],['Vyhláška 503/2022 Z. z.','https://www.slov-lex.sk/ezbierky-fe/pravne-predpisy/SK/ZZ/2022/503/']]}
  ];

  const score = a => (a.months.includes(month) ? 100 : 0) + a.base;
  const ordered = articles.slice().sort((a,b) => score(b) - score(a));
  const list = document.getElementById('articleList');
  if (list) list.innerHTML = ordered.map(a => `<button class="article-card" data-article="${a.id}"><span class="eyebrow">${a.category} · aktualizované ${a.updated}</span><h3>${a.title}</h3><p>${a.desc}</p></button>`).join('');

  const modal = document.getElementById('articleModal');
  const title = document.getElementById('articleModalTitle');
  const body = document.getElementById('articleModalBody');

  function openArticle(id) {
    const article = articles.find(a => a.id === id);
    if (!article) return;
    title.textContent = article.title;
    body.innerHTML = `${article.html}<div class="actions">${article.sources.map(([label,url]) => `<a class="btn" href="${url}" target="_blank" rel="noopener">${label} ↗</a>`).join('')}</div>`;
    modal.classList.add('open');
  }
  function closeArticle() { modal.classList.remove('open'); }

  document.addEventListener('click', e => {
    const card = e.target.closest('[data-article]');
    if (card) openArticle(card.dataset.article);
    if (e.target.closest('[data-close-modal]') || e.target === modal) closeArticle();
  });
  document.addEventListener('keydown', e => { if (e.key === 'Escape') closeArticle(); });

  window.KUSIMA_ARTICLES = { articles, openArticle };
})();
